els-ASAP auto commit file/tag xulrunner-24.8.0-1.el7_0.src.rpm

diff --git a/src/modules/freetype2/configure b/src/modules/freetype2/configure
--- a/src/modules/freetype2/configure
+++ b/src/modules/freetype2/configure
@@ -1,6 +1,6 @@
 #!/bin/sh
 #
-# Copyright 2002-2006, 2008-2010, 2013 by
+# Copyright 2002, 2003, 2004, 2005, 2006, 2008, 2009, 2010 by
 # David Turner, Robert Wilhelm, and Werner Lemberg.
 #
 # This file is part of the FreeType project, and may only be used, modified,
@@ -15,29 +15,19 @@
 
 rm -f config.mk builds/unix/unix-def.mk builds/unix/unix-cc.mk
 
-# respect GNUMAKE environment variable for backwards compatibility
 if test "x$GNUMAKE" = x; then
-  if test "x$MAKE" = x; then
-    if test "x`make -v 2>/dev/null | egrep 'GNU|makepp'`" = x; then
-      MAKE=gmake
-    else
-      MAKE=make
-    fi
-  fi
-else
-  MAKE=$GNUMAKE
+  GNUMAKE=make
 fi
 
-if test "x`$MAKE -v 2>/dev/null | egrep 'GNU|makepp'`" = x; then
-  echo "GNU make (>= 3.80) or makepp (>= 1.19) is required to build FreeType2." >&2
-  echo "Please try" >&2
-  echo >&2
-  echo "  MAKE=<GNU make command name> $0" >&2
-  echo >&2
-  echo "or" >&2
-  echo >&2
-  echo "  MAKE=\"makepp --norc-substitution\" $0" >&2
-  exit 1
+if test -z "`$GNUMAKE -v 2>/dev/null | grep GNU`"; then
+  if test -z "`$GNUMAKE -v 2>/dev/null | grep makepp`"; then
+    echo "GNU make (>= 3.80) or makepp (>= 1.19) is required to build FreeType2." >&2
+    echo "Please try" >&2
+    echo "  \`GNUMAKE=<GNU make command name> $0'." >&2
+    echo "or >&2"
+    echo "  \`GNUMAKE=\"makepp --norc-substitution\" $0'." >&2
+    exit 1
+  fi
 fi
 
 # Get `dirname' functionality.  This is taken and adapted from autoconf's
@@ -130,6 +120,6 @@ case $# in
      esac
    done ;;
 esac
-CFG=$CFG $MAKE setup unix
+CFG=$CFG $GNUMAKE setup unix
 
 # eof
